# Generated by Django 5.1 on 2024-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("workspace", "slug"), name="unqiue_board_slug_per_workspace"
            ),
        ),
    ]
