# Generated by Django 5.1 on 2024-08-22 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
