# Generated by Django 5.1 on 2024-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0002_workspace_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmembership",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("collaborator", "Collaborator")],
                default="collaborator",
                max_length=20,
            ),
        ),
    ]
