# Generated by Django 5.1 on 2024-09-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0002_board_unqiue_board_slug_per_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taskite.workspace",
            ),
        ),
    ]
