# Generated by Django 5.1 on 2024-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0003_user_current_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
