# Generated by Django 5.1 on 2024-08-17 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0003_board_boardmembership_board_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("description", models.TextField(blank=True, null=True)),
                ("sequence", models.FloatField(default=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="taskite.board",
                    ),
                ),
            ],
            options={
                "db_table": "states",
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "name"), name="unique_state_per_board"
                    )
                ],
            },
        ),
    ]
