# Generated by Django 5.1 on 2024-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0004_team_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="workspaces/logos"
            ),
        ),
    ]
