# Generated by Django 5.1 on 2024-08-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0004_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="task_sequence_counter",
            new_name="task_number_counter",
        ),
    ]
