# Generated by Django 5.1 on 2024-08-23 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0004_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_tasks",
                to="taskite.sprint",
            ),
        ),
    ]
