# Generated by Django 5.1 on 2024-08-17 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0005_rename_task_sequence_counter_board_task_number_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priorities",
                        to="taskite.board",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority",
                "verbose_name_plural": "Priorities",
                "db_table": "priorities",
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "name"), name="unique_priority_per_board"
                    )
                ],
            },
        ),
    ]
