# Generated by Django 5.1 on 2024-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0005_workspace_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="teams/avatars/"),
        ),
    ]
