# Generated by Django 5.1 on 2024-08-17 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0006_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("issue", "Issue"),
                            ("feature", "Feature"),
                            ("story", "Story"),
                            ("bug", "Bug"),
                        ],
                        default="issue",
                        max_length=10,
                    ),
                ),
                ("number", models.IntegerField(blank=True)),
                ("name", models.CharField(blank=True, max_length=10)),
                ("summary", models.CharField(max_length=225)),
                ("description", models.TextField(blank=True, null=True)),
                ("sequence", models.FloatField(default=50000)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_tasks",
                        to="taskite.board",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="taskite.task",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="priority_tasks",
                        to="taskite.priority",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="taskite.state",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "name"), name="unique_task_name_per_board"
                    )
                ],
            },
        ),
    ]
