# Generated by Django 5.1 on 2024-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0007_workspaceinvite_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceinvite",
            name="invitation_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
