# Generated by Django 5.1 on 2024-09-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0008_workspaceinvite_invitation_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspaceinvite",
            old_name="accepted_at",
            new_name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="workspaceinvite",
            name="accepted",
        ),
    ]
