# Generated by Django 5.1 on 2024-08-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0008_team_teammembership_team_members_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boardmembership",
            name="unique_member_per_board",
        ),
        migrations.AddField(
            model_name="boardmembership",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_board_memberships",
                to="taskite.team",
            ),
        ),
    ]
