# Generated by Django 5.1 on 2024-08-30 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0009_remove_boardmembership_unique_member_per_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmembership",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
