# Generated by Django 5.1 on 2024-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0010_alter_workspaceinvite_invitation_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"), name="unqiue_user_per_workspace"
            ),
        ),
    ]
