# Generated by Django 5.1 on 2024-09-01 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0012_alter_boardmembership_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="members",
            new_name="users",
        ),
        migrations.AddField(
            model_name="board",
            name="teams",
            field=models.ManyToManyField(
                related_name="boards",
                through="taskite.BoardMembership",
                to="taskite.team",
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="taskite.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Invite",
                "verbose_name_plural": "Workspace Invites",
                "db_table": "workspace_invites",
            },
        ),
    ]
