# Generated by Django 5.1 on 2024-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0013_rename_members_board_users_board_teams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
