# Generated by Django 5.1 on 2024-09-29 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0013_upload_bucket_upload_uploaded_by_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurgedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bucket", models.CharField(default="local", max_length=124)),
                ("key", models.CharField(max_length=225)),
                ("purged_at", models.DateTimeField()),
            ],
            options={
                "db_table": "purged_assets",
            },
        ),
        migrations.CreateModel(
            name="UnusedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bucket", models.CharField(default="local", max_length=124)),
                ("key", models.CharField(max_length=225)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "unused_assets",
            },
        ),
    ]
