# Generated by Django 5.1 on 2024-09-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0015_alter_unusedasset_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unusedasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
