# Generated by Django 5.1 on 2024-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0016_alter_unusedasset_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
