# Generated by Django 5.1 on 2024-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0020_tasklabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                related_name="assigned_label_tasks",
                through="taskite.TaskLabel",
                to="taskite.label",
            ),
        ),
    ]
