# Generated by Django 5.1 on 2024-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0021_task_labels"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("board", "name"), name="unqiue_label_name_per_board"
            ),
        ),
    ]
