# Generated by Django 5.1 on 2024-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0022_label_unqiue_label_name_per_board"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tasklabel",
            constraint=models.UniqueConstraint(
                fields=("task", "label"), name="unique_label_per_task"
            ),
        ),
    ]
