# Generated by Django 5.1 on 2024-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0023_tasklabel_unique_label_per_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="org_size",
            field=models.CharField(default="1", max_length=20),
        ),
    ]
