# Generated by Django 5.1 on 2024-10-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0024_workspace_org_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
