# Generated by Django 5.1 on 2024-10-15 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0026_boardteampermission_boardpermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="teams",
        ),
        migrations.AlterField(
            model_name="board",
            name="users",
            field=models.ManyToManyField(
                related_name="boards",
                through="taskite.BoardPermission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BoardMembership",
        ),
    ]
