# Generated by Django 5.1 on 2024-10-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0027_remove_board_teams_alter_board_users_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="unqiue_board_slug_per_workspace",
        ),
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.SlugField(blank=True, max_length=124, unique=True),
        ),
    ]
