# Generated by Django 5.1 on 2024-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0028_remove_board_unqiue_board_slug_per_workspace_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PurgedAsset",
        ),
        migrations.DeleteModel(
            name="UnusedAsset",
        ),
        migrations.DeleteModel(
            name="Upload",
        ),
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="workspaces/logos/"
            ),
        ),
    ]
