# Generated by Django 5.1 on 2024-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taskite",
            "0029_delete_purgedasset_delete_unusedasset_delete_upload_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="boards/covers/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="teams/avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/avatars/"),
        ),
    ]
