# Generated by Django 5.1 on 2024-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0030_alter_board_cover_alter_team_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("maintainer", "Maintainer"),
                    ("collaborator", "Collaborator"),
                    ("guest", "Guest"),
                ],
                default="collaborator",
                max_length=20,
            ),
        ),
    ]
