# Generated by Django 5.1 on 2024-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0031_alter_workspacemembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.UniqueConstraint(
                fields=("board", "name"), name="unique_sprint_name_per_board"
            ),
        ),
    ]
