# Generated by Django 5.1 on 2024-10-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0032_sprint_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_password_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
