# Generated by Django 5.1 on 2024-10-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0035_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
