# Generated by Django 5.1 on 2024-10-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0036_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
