# Generated by Django 5.1 on 2024-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0038_backfill_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
