# Generated by Django 5.1 on 2024-10-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0040_taskattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="comment_type",
            field=models.CharField(default="update", max_length=10),
        ),
    ]
