# Generated by Django 5.1 on 2024-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0041_taskcomment_comment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("attachment", "Attachment"),
                    ("comment", "Comment"),
                    ("label", "Label"),
                    ("priority", "Priority"),
                    ("state", "State"),
                ],
                default="default",
                max_length=10,
            ),
        ),
    ]
