# Generated by Django 5.1 on 2024-10-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0043_alter_taskcomment_activity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskcomment",
            name="activity_type",
        ),
    ]
