# Generated by Django 5.1 on 2024-11-13 15:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0048_board_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="checklists",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
