# Generated by Django 5.1 on 2024-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0049_task_checklists_task_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="filename",
            field=models.CharField(default="default"),
            preserve_default=False,
        ),
    ]
