# Generated by Django 5.1 on 2024-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0054_newslinecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsline",
            name="allow_comment",
            field=models.BooleanField(default=True),
        ),
    ]
