# Generated by Django 5.1 on 2024-12-11 04:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0056_newslineread"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="newsline",
            managers=[
                ("published_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="auto_assign_domain",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="auto_assign_membership",
            field=models.BooleanField(default=False),
        ),
    ]
