# Generated by Django 5.1 on 2024-12-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taskite",
            "0057_alter_newsline_managers_workspace_auto_assign_domain_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_generic_email",
            field=models.BooleanField(default=True),
        ),
    ]
