# Generated by Django 5.1 on 2024-12-15 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0058_user_is_generic_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="estimate_type",
            field=models.CharField(
                choices=[
                    ("point", "Point"),
                    ("category", "Category"),
                    ("time", "Time"),
                ],
                default="time",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="is_estimate_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estimate_type",
                    models.CharField(
                        choices=[
                            ("point", "Point"),
                            ("category", "Category"),
                            ("time", "Time"),
                        ],
                        db_index=True,
                        default="time",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("value", models.CharField(max_length=30)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="taskite.board",
                    ),
                ),
            ],
            options={
                "db_table": "estimates",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_tasks",
                to="taskite.estimate",
            ),
        ),
    ]
