# Generated by Django 5.1 on 2024-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0059_board_estimate_type_board_is_estimate_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimate",
            name="estimate_type",
        ),
        migrations.AddField(
            model_name="estimate",
            name="key",
            field=models.IntegerField(default=1),
        ),
    ]
