# Generated by Django 5.1 on 2024-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0060_remove_estimate_estimate_type_estimate_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("board",),
                name="unique_active_sprint_per_board",
            ),
        ),
    ]
