# Generated by Django 5.1 on 2024-12-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0062_board_is_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=124, unique=True
            ),
        ),
    ]
